version: '3.8'

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 9000:6379
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=llm_user
      - POSTGRES_PASSWORD=llm_pass
      - POSTGRES_DB=llm_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    command: ./entrypoint.sh
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 5001:5000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    env_file:
      - .env.dev
    volumes:
      - jounce:/opt/jounce
    command: ./startworker.sh
    depends_on:
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_backend
    env_file:
      - .env.dev
    volumes:
      - jounce:/opt/jounce
    command: celery -A src.celery beat --loglevel=DEBUG
    depends_on:
      - celery_worker

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  redis_data:
  jounce:
