"""empty message

Revision ID: 9ca5a9c08324
Revises: c5880cb0d888
Create Date: 2024-09-13 18:15:18.952506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca5a9c08324'
down_revision = 'c5880cb0d888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('llm_benchmark_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('metric_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'llms', ['llm_id'], ['id'])
        batch_op.create_foreign_key(None, 'metrics', ['metric_id'], ['id'])
        batch_op.drop_column('model')
        batch_op.drop_column('metric')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_benchmark_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('metric_id')
        batch_op.drop_column('llm_id')

    op.drop_table('metrics')
    op.drop_table('llms')
    # ### end Alembic commands ###
