"""empty message

Revision ID: e9306d4a164d
Revises: 9ca5a9c08324
Create Date: 2024-09-13 19:27:01.088903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9306d4a164d'
down_revision = '9ca5a9c08324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_benchmark_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_benchmark_results_llm_id'), ['llm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_benchmark_results_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index('ix_llm_metric', ['llm_id', 'metric_id'], unique=False)

    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.drop_constraint('llms_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_llms_name'), ['name'], unique=True)

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_value', sa.Float(), nullable=True))
        batch_op.drop_constraint('metrics_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_metrics_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_name'))
        batch_op.create_unique_constraint('metrics_name_key', ['name'])
        batch_op.drop_column('max_value')
        batch_op.drop_column('min_value')

    with op.batch_alter_table('llms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llms_name'))
        batch_op.create_unique_constraint('llms_name_key', ['name'])

    with op.batch_alter_table('llm_benchmark_results', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_metric')
        batch_op.drop_index(batch_op.f('ix_llm_benchmark_results_metric_id'))
        batch_op.drop_index(batch_op.f('ix_llm_benchmark_results_llm_id'))

    # ### end Alembic commands ###
